### ISSUE TITLE
finalize authentication with Google

### ISSUE THREAD

**Issue by baudoin-csp** [Swent-Fall-2024-team-10/leazy#29]

**Comment by ShinUrech** [comment]
We face problems with access to OAuth. I created a separate firebase project and an app sample to test where the problem comes from. 

- I tried with react-native-google-signin/google-signin package but it requires builds on IOS and android, which we cannot do without an apple developper account. 

- I tried with expo-auth session (with a project from last Swent class that implemented the authentication with a browser based solution: uniconnect), which turned out to be unsuccessful too. (see picture)
![WhatsApp Image 2024-10-16 at 17 23 23](https://github.com/user-attachments/assets/08d3be42-427b-41a1-90d4-e92fd237b71d)
